export enum Specifications {
  FINANCIAL = 'FINANCIAL',
  HAS_PRIVATE_WEB_RESOURCES = 'HAS_PRIVATE_WEB_RESOURCES',
  HAS_PUBLIC_WEB_RESOURCES = 'HAS_PUBLIC_WEB_RESOURCES',
  DEFENCE_SYSTEM = 'DEFENCE_SYSTEM',
  SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA = 'SPECIAL_OR_BIOMETRIC_OFFICIALS_PERSONAL_DATA',
  IMPACT_ON_PUBLIC_PERCEPTION = 'IMPACT_ON_PUBLIC_PERCEPTION',
  BASIC = 'BASIC',
  GOVERNMENT = 'GOVERNMENT',
  INDUSTRY = 'INDUSTRY',
}